version: "3.8"

services:
  backend:
    build:
      context: ./miss-bug-proj-backend
      dockerfile: Dockerfile
    ports:
      - "3030:3030"
    volumes:
      - ./miss-bug-proj-backend/data:/usr/src/app/data
    environment:
      - JWT_SECRET=missBugSecretKey

  frontend:
    build:
      context: ./miss-bug-starter-react-vite
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend


