version: '3.8'

services:
  backend:
    image: miss-bug-backend:stable
    build:
      context: ./miss-bug-proj-backend
      dockerfile: Dockerfile
      
    ports:
      - '3030:3030'
    environment:
      - JWT_SECRET=missBugSecretKey
    volumes:
      - ./miss-bug-proj-backend/data:/usr/src/app/data

  frontend:
    image: miss-bug-frontend:slim
    build:
      context: ./miss-bug-starter-react-vite
      dockerfile: Dockerfile
    ports:
      - '8080:80'
    depends_on:
      - backend
